version: "3"

silent: true

tasks:
  dc:
    cmds:
      - task: decrypt:env
      - docker-compose {{.CLI_ARGS}}
  dce:
    cmds:
      - task: decrypt:env
      - docker-compose -f docker-compose.yml -f docker-compose.extra.yml {{.CLI_ARGS}}

  gen:sm:
    internal: true
    vars:
      CONTAINERS_COUNT_BEFORE:
        sh: expr $(task dc -- ps | wc -l)
    cmds:
      # Close Containers started by this task if These containers were not already running
      - defer: $([ "{{.CONTAINERS_COUNT_BEFORE}}" = 1 ]) && task dc -- down $SERVICES
      - task dc -- up -d $SERVICES
      - $([ "{{.CONTAINERS_COUNT_BEFORE}}" = 1 ]) && sleep 5 || sleep 0
      - task dc -- cp $SCRIPT_PATH db:/sitemap-gen.sh
      - task dc -- exec db sh -c "/sitemap-gen.sh"
      - mkdir -p $RESULT_FILE_PATH
      - task dc -- cp db:/tmp/file.txt $RESULT_FILE_PATH/file.json
    env:
      SCRIPT_PATH: ./pgsql-scripts/sitemap-gen.sh
      RESULT_FILE_PATH: ./print-wiki/in
      SERVICES: db wiki traefik

  record:wiki:
    dir: print-wiki
    cmds:
      - task: gen:sm
      - npm run start

  decrypt:env:
    internal: true
    cmds:
      - sops --input-type dotenv --output-type dotenv  -d sops.env > .env
